spring.application.name=contact

spring.datasource.url=jdbc:postgresql://localhost:5432/bus_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
